// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANuQGOqXLNWsfIz4Os0E8ZfMJTtUMVUWs',
    appId: '1:508566735913:web:8eeb84c6c54a91ecace038',
    messagingSenderId: '508566735913',
    projectId: 'khiat-590bc',
    authDomain: 'khiat-590bc.firebaseapp.com',
    storageBucket: 'khiat-590bc.appspot.com',
    measurementId: 'G-LBDJC2HF3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_s-iiTVwIA1vashKWmv2KlOEqx5_rGf4',
    appId: '1:508566735913:android:ca47daa76ebf1918ace038',
    messagingSenderId: '508566735913',
    projectId: 'khiat-590bc',
    storageBucket: 'khiat-590bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5YQzOj_uhAVHUma6yZYKpOUFpGHzt6Kk',
    appId: '1:508566735913:ios:c18770970703b9ceace038',
    messagingSenderId: '508566735913',
    projectId: 'khiat-590bc',
    storageBucket: 'khiat-590bc.appspot.com',
    iosBundleId: 'com.example.khiat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5YQzOj_uhAVHUma6yZYKpOUFpGHzt6Kk',
    appId: '1:508566735913:ios:c18770970703b9ceace038',
    messagingSenderId: '508566735913',
    projectId: 'khiat-590bc',
    storageBucket: 'khiat-590bc.appspot.com',
    iosBundleId: 'com.example.khiat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANuQGOqXLNWsfIz4Os0E8ZfMJTtUMVUWs',
    appId: '1:508566735913:web:aea33a2015e43859ace038',
    messagingSenderId: '508566735913',
    projectId: 'khiat-590bc',
    authDomain: 'khiat-590bc.firebaseapp.com',
    storageBucket: 'khiat-590bc.appspot.com',
    measurementId: 'G-04YGN8E00W',
  );
}
